// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1jZlPZTckkhVkRJVelV5P04NGnlSCkpM',
    appId: '1:501258486458:web:51f76ad02b258d70c77883',
    messagingSenderId: '501258486458',
    projectId: 'whatsappchat-23194',
    authDomain: 'whatsappchat-23194.firebaseapp.com',
    storageBucket: 'whatsappchat-23194.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN4ayi3KIOJnsTY4f0Jko4ARDQKUgHaxo',
    appId: '1:501258486458:android:8c56dd7cb60dbf88c77883',
    messagingSenderId: '501258486458',
    projectId: 'whatsappchat-23194',
    storageBucket: 'whatsappchat-23194.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOUhz7IIJlX41QxqgCUcti6_UX5b1-StM',
    appId: '1:501258486458:ios:f355a4a7fa496d84c77883',
    messagingSenderId: '501258486458',
    projectId: 'whatsappchat-23194',
    storageBucket: 'whatsappchat-23194.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
